### ISSUE TITLE
Unminified plain-draggable.min.js

### ISSUE THREAD

**Issue by David-Carty** [anseki/plain-draggable#110]
Hi Anseki,

npm i plain-draggable
cd node_modules/plain-draggable
npm i

Got quite a few errors.  Really speaking I just need the unminified version of plain-draggable.min.js.  Typically the only file on GitHub that does not have an unminified version.  Is there any chance that you could push this to GitHub?  The work I'm doing is just a prototype in vanilla and doesn't even need a build system. Best David

**Comment by anseki** [comment]
Hi @David-Carty, thank you for the comment.
I don't know why you failed the installing because you didn't tell about the errors.
Anyway, the `.min` in a file name means minified file. That is, a file name that doesn't include `.min` is not minified.
You can get all files of PlainDraggable at [this repository](https://github.com/anseki/plain-draggable). And you can do `git clone` to get data of the repository.

**Comment by David-Carty** [comment]
The error message from npm is huge, so I didn't include it.  Its related to babel and I'm just so busy at mo, to analyse.  Unfortunately, there is only a minified version of this file: https://github.com/anseki/plain-draggable/blob/master/plain-draggable.min.js
So, none of the unminfied files run in the browsers because they contain imports relevant to the build, which I can't run on my local machine.   I need to work on an unminified version because it doesn't support a feature that I need.  Any chance that you can transpile but not minify so there is an unminified version that runs in the browser? Thanks again for your time. David.

**Comment by anseki** [comment]
If you want the unminified code for test, you can find the test version in `test` directory.

**Comment by David-Carty** [comment]
Thanks again Anseki works a treat.  Really appreciate that. Best David.

**Comment by anseki** [comment]
:smile:
