### ISSUE TITLE
Wrong position after window resize in case of using CSS scale

### ISSUE THREAD

**Issue by catybar** [anseki/plain-draggable#125]
Hello, thank you for implementing and supporting such a great project!

Here another issue relates to problem with CSS scale, and in this comment https://github.com/anseki/plain-draggable/issues/13#issuecomment-449687383 you provided a fiddle https://jsfiddle.net/5rzkxpaf/. I use this fiddle to reproduce problem i'm talking about.

Take a look at the gif - after window's resize the red square start moving to right-bottom direction and then it even disappears. Note, to reproduce it firstly you need to move the square from it's initial position.

Could you please advise some workaround to overcome this problem?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/96011451/204557538-a53b0cc0-1dac-485f-b7d0-0450af79d4bc.gif)

**Comment by anseki** [comment]
Hi @catybar, thank you for the comment.
Best advice for you is that avoid using the `scale` property because that is not good way to change the size as I said in the past issue.
That should be moved regardless of resizing window and scrolling and others because position is lost when the mouse pointer is released once.
The `scale` changes only the transformation without changing view.
You had better use e.g. SVG that has `viewBox` to allows to really change scale of the view.

**Comment by catybar** [comment]
Ok, got it, thank you!

**Comment by anseki** [comment]
:smile:
