### ISSUE TITLE
Batch move by drag & drop

### ISSUE THREAD

**Issue by kanban3333** [anseki/plain-draggable#143]
Hi, I am looking to combine plain-draggable and leader-line to create the following process.
　1. Drag the mouse to select multiple blocks
　2. Move all selected blocks at once by drag & drop
　　※If a line is drawn on the block at this time, the position of the line is also updated.
　3. Multiple selection of the moved blocks will be deselected and they can be moved individually.
　
I have tried everything, but cannot get it to work. Can it be implemented in the first place? I would appreciate it if you could tell me.
※I translated it into English using a tool. Sorry for the funny parts.)

Here is a sample we created.
https://jsfiddle.net/kanban3333/6a9odcxb/13/

**Comment by anseki** [comment]
Hi @kanban3333, thank you for the comment.
To synchronize those, you can use `onMove*` event listeners of  PlainDraggable instance instead of `mousemove` event listener.
Also, `left` and `top` properties of  the instance (not CSS properties) allow you to move the item correctly in consideration of the container.
For example: https://jsfiddle.net/8hsc6dj4/

**Comment by kanban3333** [comment]
Thank you for the great sample.

I am sorry, but due to my technical difficulties, I am having a hard time selecting a batch of objects to move by dragging and deselecting the batch after the move.

I may have other questions, so please give me a little more time.

**Comment by kanban3333** [comment]
これ以上時間を掛ける訳にはいかないのでここで完了にしたいと思います。

助けてくれてありがとうございます！

**Comment by anseki** [comment]
😄
