### ISSUE TITLE
sortable list example 

### ISSUE THREAD

**Issue by yairEO** [anseki/plain-draggable#40]
Hi, very good documentation and impressive demo page. good work.

Only problem is the "sortable list" demo, which feels very slow and also has a bug, where any element cannot be dragged to be the last one.

I would like dragging & sorting to feel much much faster, and the way it behaves now is not smooth enough for production-level projects

**Comment by anseki** [comment]
Hi @yairEO, thank you for the comment.
I couldn't reproduce that bug in my environments (Google Chrome, Firefox, MS Edge, Safari, and others).
All items can be dragged to the bottom of the list.
Could you tell me your environment (name and version of your web browser)?

**Comment by yairEO** [comment]
windows 10, latest Chrome:

![GIF](https://user-images.githubusercontent.com/845031/70231483-b20e5280-175a-11ea-830e-f79ef586311b.gif)

**Comment by anseki** [comment]
Thank you for the information and the GIF.
It seems that only your environment can't drag that.
See:
![GIF](https://user-images.githubusercontent.com/4763469/70233781-962e9f00-17a2-11ea-9b9a-5cbcc1bc2b27.gif)
That works fine in my all environments for test, and that problem has never even once be reported before.
Maybe your Chrome extension, plugin or something avoids that.

**Comment by yairEO** [comment]
I'm on a fresh windows install and also tried it in incognito. still same bug.
Chrome: `Version 78.0.3904.108 (Official Build) (64-bit)`

on Firefox it works well.

Are you testing on Windows 10 as well?

**Comment by anseki** [comment]
I tested that on Windows 10 and Google Chrome and recorded it to GIF because you are using those.
And also, I of course tested on Windows 7 and Windows 8.1, that works fine on those.

That is strange. That has never even once be reported before. You can read the source code, it is very short.
I can do nothing because that can't be reproduced, sorry.

Anyway, if you want a library for sorting, you had better use another library because this is not a library for sorting.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
