### ISSUE TITLE
Is some Drop-functionality planned for this library ?

### ISSUE THREAD

**Issue by Bomchickawowow** [anseki/plain-draggable#62]
Hi,
Your library works realy well, but unfortunally it is only usefull for a limited amount of cases, because of the lack of Drop Events. I am fully aware of that this library is only focused on drag features, but have you considered to implement Drop functionalites for the future ?

**Comment by anseki** [comment]
Hi @Bomchickawowow, thank you for the comment.
Supporting the drop-event is not required because the `onDragEnd` that is more flexible is supported. And also, the drop-event has to be related to another element (i.e. receiver). That is, the library is no longer *Plain*Draggable if it supports the drop-event.
Actually, You can implement that easily by the `onDragEnd`.
If you really want the drop-event, you had better use another great library or framework that supports that instead.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
