### ISSUE TITLE
How to Grab dragable leader-line when click on button

### ISSUE THREAD

**Issue by rrdevlmc** [anseki/plain-draggable#86]
Hi @anseki, Thank you for providing awesome library. I have draggable leader line when click on button check the link [https://jsfiddle.net/1f5w4qr0/](url). when click on line button line will appear and then drag to the designation, But how to hold on line when click on button then drag to the destination. Here the example of draw line when click on button [https://jsfiddle.net/6Lybe0jm/](url). Can you please guide me using plan-draggable to mouse move the line

**Comment by anseki** [comment]
Hi @rrdevlmc, thank you for the comment.
Sorry, my English is poor.
Could you explain more?
What does the "hold on line" mean?
What is problem in the example?

**Comment by rrdevlmc** [comment]
Hi @anseki , In this code [https://jsfiddle.net/1f5w4qr0/](url) when click on  button then line will appear after drag the line to destination point. But [https://jsfiddle.net/6Lybe0jm/.](url) In this example click on source one then line will mouseover untill when click to one of destination. Can we do this same using plain-draggable with leaderline [()](https://jsfiddle.net/1f5w4qr0/).

**Comment by anseki** [comment]
I clicked links in your comment, but examples were not shown. The URLs seem to be wrong.
Anyway, do you mean that you want a LeaderLine that connect to a target element by dragging a handle of the line?

**Comment by rrdevlmc** [comment]
Ohh Sorry links are --> https://jsfiddle.net/1f5w4qr0/ and Another one is https://jsfiddle.net/6Lybe0jm/

**Comment by anseki** [comment]
Was I wrong in my conjecture?

**Comment by rrdevlmc** [comment]
Hi @anseki, Can you please checkout this example code https://jsfiddle.net/ouvnph9L/ onDrag change color is notworking when mouse move draggable line.

**Comment by anseki** [comment]
Your code changes `startPlugColor`/`endPlugColor` (NOT `color`) in `onDrag` event listener, then it seems to be working fine.
If you want to change `color` (not `startPlugColor`/`endPlugColor`), you have to specify `color` option.

**Comment by rrdevlmc** [comment]
But it's not firing onDrag method that's why it's not changing color to lime

**Comment by anseki** [comment]
See this: https://jsfiddle.net/zxwde58j/
You should see that the `onDrag` event listener was called correctly in console of your web browser (Press keys: <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd>).
Also, as I said, your code doesn't change the `color`, it changes the `startPlugColor`/`endPlugColor` only when it is snapped.
If you want to change `color` (not `startPlugColor`/`endPlugColor`), you have to specify `color` option.

**Comment by anseki** [comment]
Sorry, my English is poor.
Why mouse moving is not stopping?
Also, did you confirm that the `onDrag` event listener was called correctly? (You said that it is not called.)

**Comment by rrdevlmc** [comment]
No @anseki, Not working as perfect see this example https://jsfiddle.net/6Lybe0jm/ when click on purple box after that mouse move is activated and then click on any below boxes line draw happed. but https://jsfiddle.net/zxwde58j/ this example using same logic with plain-draggable but coming expected. See this example https://jsfiddle.net/ouvnph9L/1/ without mouse move just plain-draggable working good just like same as when using mouse move expected same result.

**Comment by anseki** [comment]
That is correct behavior. PlainDraggable is a library to allow an element to be dragged.
See document: https://github.com/anseki/plain-draggable
That is, the element can't move without pressing mouse-button because "mouse-moving" without pressing mouse-button is NOT "mouse-dragging".
Your example accepts "mouse-moving" by using `mousemove` event, not PlainDraggable.
Do you mean that you want a moving element by "mouse-moving" rather than "mouse-dragging"?

**Comment by anseki** [comment]
That is correct behavior. PlainDraggable is a library to allow an element to be dragged.
See document: https://anseki.github.io/plain-draggable/
That is, the element can't move without pressing mouse-button because "mouse-moving" without pressing mouse-button is NOT "mouse-dragging".
Your example accepts "mouse-moving" by using `mousemove` event, not PlainDraggable.
Do you mean that you want a moving element by "mouse-moving" rather than "mouse-dragging"?

**Comment by rrdevlmc** [comment]
Yes @anseki, I want drag/move leader-line when move the mouse

**Comment by anseki** [comment]
You have to understand the difference between the "mouse-moving" and the "mouse-dragging".
Note that both are fired by moved mouse but only the "mouse-dragging" requires pressing mouse-button.
And, you have to handle the `mousemove` event instead of using PlainDraggable because it is a library for the "mouse-dragging", not the "mouse-moving".

**Comment by anseki** [comment]
In other words, your example that handles the `mousemove` event accepts the "mouse-moving".
And your example that uses PlainDraggable only accepts the "mouse-dragging".

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
