### ISSUE TITLE
Can a snap occur only on mouseup?

### ISSUE THREAD

**Issue by PedanticHacker** [anseki/plain-draggable#92]
This is not so much an issue but rather a question, since I have just found this wonderful library.

I want to know whether a snap can occur only after releasing the mouse button (basically a snap only on mouseup). Is this possible? Thank you in advance!

**Comment by anseki** [comment]
Hi @PedanticHacker, thank you for the comment.
Sorry, I couldn't understand that well.
Do you mean that you want to make the element move toward a wall or something when a mouse button was released on the element in a place near the wall or something?

**Comment by PedanticHacker** [comment]
Well, I am trying to make a drag&drop chessboard. So a dragged chess piece should snap to the center of a chessboard square only after a mouse button release. Is that possible?

**Comment by anseki** [comment]
It seems that the behavior is not the Snap of the library because the element did already finish the moving. And also, it is unrelated to dragging, it is just a moving an element.
You can do that easily. For example: https://jsfiddle.net/3uzbjpdk/

**Comment by PedanticHacker** [comment]
Honestly, I don't know why I asked you this. It was a premature question. I can't even make a simple drag. My code below doesn't work. Please tell me what on Earth am I missing.

```
<!doctype html>
<html>
<head>
    <script src="https://unpkg.com/plain-draggable@2.5.14/plain-draggable.min.js">
    </script>
</head>
<body>
    <div id="drag">DRAG!</div>
    <script>
        window.addEventListener("load", function() {
            "use strict";
            var draggable = new PlainDraggable(document.getElementById("drag"), {
                snap: 10
            });
        });
    </script>
</body>
</html>

```

**Comment by anseki** [comment]
I copied your code and pasted it to JSFiddle, then that seems to work fine.
https://jsfiddle.net/wom8hq6k/

I also don't know why you asked.
Of course I hope that I help you if I can. However, as I said in my first comment (https://github.com/anseki/plain-draggable/issues/92#issuecomment-861091401), I couldn't understand what you want to do, sorry.

Of course the library supports HTML and SVG.
If you want to know about the library, see document:
https://anseki.github.io/plain-draggable/
There is an example for SVG also in the document.

**Comment by anseki** [comment]
Do you want to make an UI like this?
https://jsfiddle.net/70xskwvp/
However, I think that this is not good UI for usability.

**Comment by anseki** [comment]
FYI;
Both Python and JavaScript (i.e. ECMAScript) are easy to acquire, learn, and use, also those are called LL (Lightweight Languages).
Therefore, you may be able to learn ECMAScript if you could learn Python.

**Comment by PedanticHacker** [comment]
Thanks for all this.

Let me be more elaborate here. My HTML code posted was being rendered in the current latest version of the Chrome browser on Windows 10. On hovering the mouse pointer over the draggable element, the cursor changes from an arrow (as it always is) to an open hand. And then during dragging, the cursor changes from the open hand to a closed hand, but the element is not actually dragged, it stays at the same coordinates. I noticed while inspecting the code in Chrome during dragging that `transform=translate(0, 0)` is always at those coordinates, that's why the actual drag does not occur. I don't understand why my code works on JSFiddle but not in Chrome.

**Comment by anseki** [comment]
Try this: https://github.com/anseki/plain-draggable/issues/92#issuecomment-861593825
And read again CSS.
Maybe, your mistake is that you didn't give space for the draggable element moving.
And also, see this: https://github.com/anseki/plain-draggable/issues/92#issuecomment-861596452
Is this not what you want?

**Comment by PedanticHacker** [comment]
I've fiddled with my code on JSFiddle (my fiddled code here: https://jsfiddle.net/4wjmby05/) and removed all CSS code. Now the dragging is not possible. How can CSS play such a major role in the dragging part?

Also, why can't I use `g` elements as draggable targets? I think it's because the `g` element doesn't have a bounding rect. But would it work if I enclose it inside an element that **does** have a bounding rect?

**Comment by anseki** [comment]
Could you answer to the my question (https://github.com/anseki/plain-draggable/issues/92#issuecomment-861675421) before your new questions?
Because that may help me to understand what you want to do.

**Comment by PedanticHacker** [comment]
> Maybe, your mistake is that you didn't give space for the draggable element moving.

Well, your documentation says that the draggable element will get as much space as is provided by its parent. And since my draggable <div> is a direct child of the <body>, then that draggable <div> should get as much space as the <body> has. So I don't understand why the dragging is restricted.

**Comment by anseki** [comment]
Could you answer to the my question (https://github.com/anseki/plain-draggable/issues/92#issuecomment-861675421) before your new questions?
Because that may help me to understand what you want to do.

**Comment by anseki** [comment]
You seem to mistake the size of `<body>` and the size of the document.
1. That is correct behavior. That is specification of HTML and CSS, it is unrelated to PlainDraggable. By default, moving of the draggable element is restricted to the inside of its parent element (See document: https://anseki.github.io/plain-draggable/#options-containment). Since you removed the CSS, the space for moving also was removed. Check the size of `<body>` element and `<div id="drag">` element by using DevTools of your browser.
2. Yes, elements that have a bounding-box are accepted. See document: https://anseki.github.io/plain-draggable/#constructor
3. That initializes animation. See document: https://developer.mozilla.org/en-US/docs/Web/CSS/transition

Your questions are unrelated to PlainDraggable. You should learn HTML and CSS before ECMAScript and PlainDraggable because you will handle DOM with ECMAScript. You confuse more if you don't learn these.
That is, you should learn in this order:
1. HTML
2. CSS
3. ECMAScript
4. DOM
5. PlainDraggable

And also, I couldn't understand what you want to do because you never answer to the my question.

**Comment by PedanticHacker** [comment]
> And also, I couldn't understand what you want to do because you never answer to the my question.

I want to create a chessboard with draggable pieces. See image below.

![](https://cdn5.vectorstock.com/i/1000x1000/52/79/chess-board-with-chess-pieces-vector-1765279.jpg)

**Comment by PedanticHacker** [comment]
Look at this:
```
#item:not(.plain-draggable-dragging) {
  transition: transform 100ms ease-in;
}
```

I have asked what is this, and you answered:
> 3. That initializes animation. See document: https://developer.mozilla.org/en-US/docs/Web/CSS/transition

I am interested in finding out why the `:not` thing has to be there in CSS. Well, I googled about `:not`, but now I don't understand why transition has to happen only for the `#item` which classes are **not** `.plain-draggable-dragging`. This is confusing to me.

**Comment by anseki** [comment]
Could you answer to the my question before your new questions?
Because that may help me to understand what you want to do. (Unfortunately, your image doesn't help me because the image never work, important thing is its behavior.)
My question is here: https://github.com/anseki/plain-draggable/issues/92#issuecomment-861596452
Please understand that I hope that I help you. Can't you understand my wrong English? The, you never answer to the my question? If so, sorry. And please read my comment again please.

**Comment by PedanticHacker** [comment]
> Do you want to make an UI like this?
> https://jsfiddle.net/70xskwvp/
> However, I think that this is not good UI for usability.

Yes, my UI should resemble your example UI. But instead of a 5×5 grid, I want to have an 8×8 grid, and instead of a draggable blue rectangle, I want to have SVG pieces that will be draggable and snap to the center of a square when dropped. The snapping in your example UI is exactly what I want, maybe `50ms ease-in` instead of `100ms ease-in`.

**Comment by anseki** [comment]
Thank you for the answering to the my question. That very helps me to understand what you want to do.

Also, could you reply to the my answers (https://github.com/anseki/plain-draggable/issues/92#issuecomment-862330942)?
For example, did you understand the size of `<body>` element?
You did new questions instead of replying to me, but those are related to your new questions. That is, those are important information for your new questions. Please understand it.

**Comment by PedanticHacker** [comment]
Sorry for all the stupid questions. I will try with drag & drop that HTML5 provides.

**Comment by anseki** [comment]
It's OK. :smile: 
So, could you close this issue?

**Comment by PedanticHacker** [comment]
HTML, CSS and Javascript are very interesting, however. It's too bad you didn't want to answer my questions.

**Comment by anseki** [comment]
Yes, you should learn those as I said (https://github.com/anseki/plain-draggable/issues/92#issuecomment-862330942).
When you learned those in the order that I recommended, you should understand your questions.

Also, as I said repeatedly, your idea is not good UI for usability. You maybe know that.

Sorry that you discontented with my answers. We may have been able to help you more if you reply. Understand that you have to give information to help you.
Good luck :smile:
